spring:
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://localhost:8080
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /api/orders/${segment}
            - AddRequestParameter=foo, bar
            - RemoveRequestHeader=X-Remove-Header
            - Retry=5
